#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

// #define PRINT_COM_CAN_REC
// #define PRINT_MONITORING_RESET


#define MAIN_LOOP_FPS       50
#define MAIN_LOOP_DELAY     (1.0/MAIN_LOOP_FPS)


#define ORDERS_COUNT        100

#define SERVO_PWM_PERIOD    (1.0/50)

#endif // CONFIG_H_INCLUDED
