
all: build

build:
	make -C QBouge build
	make -C QReflechi build
	make -C QEntreQSort build

stats:
	make -C QBouge stats
	make -C QReflechi stats
	make -C QEntreQSort stats

soft_re:
	make -C QBouge soft_re
	make -C QReflechi soft_re
	make -C QEntreQSort soft_re
